### ISSUE TITLE
Multiple Libraries

### ISSUE THREAD

**Issue by zackotronic** [jeremehancock/Posteria#5]
If you have multiple movie libraries and tv libraries, when you import the from the first library everything works. As soon as you import from another library, the posters from the first import are "orphaned".

**Comment by jeremehancock** [comment]
Thank you so much for the report. I am working on a fix now!

**Comment by jeremehancock** [comment]
@zackotronic Can you do me a favor and check to see if the same issue happens with TV Seasons?

**Comment by zackotronic** [comment]
Yes it does.

**Comment by jeremehancock** [comment]
@zackotronic 
I have just pushed an update that should resolve the issues.

I recommend starting completely from the start. So manually remove the local Posteria posters and re-import.

There is still a more edge case bug that is similar. If you completely remove a Library form Plex the files do not get marked as orphaned, but they are. I am working on that now.

I will leave this open so you can let me know if you have any issues with the update. 

Thanks again

**Comment by jeremehancock** [comment]
@zackotronic I just pushed an update that should also fix the edge case of removing a library completely from Plex.

Thanks again

**Comment by zackotronic** [comment]
it appears to work now! thanks!

**Comment by dmandrone** [comment]
Hello! I just wanted to note that I am still experiencing this issue. I just pulled a fresh version of the app from the Unraid Community Apps list. I have a library for Movies and Anime Movies. I pulled the posters for Anime Movie Collections first, then I ran the Movie Collections afterwards and all Anime Movie Collection posters were marked as orphaned.
